# استخدام Node.js الإصدار 20.15
FROM node:20.15

# تحديد مجلد العمل
WORKDIR /usr/src/app

# نسخ ملفات الحزم وتثبيتها
COPY package*.json ./
RUN npm install

# نسخ باقي الملفات
COPY . .

# تشغيل n8n
CMD ["npx", "n8n", "start"]
